In [1]:
import pandas as pd
data = pd.read_csv('UberDatasetFiltered.csv')

In [3]:
# Convert times to just the hour
data['START_DATE'] = pd.to_datetime(data['START_DATE']).dt.hour
data['END_DATE'] = pd.to_datetime(data['END_DATE']).dt.hour
data

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,START_STATE,STOP_STATE,START_LOC,STOP_LOC,START_LAT,START_LONG,STOP_LAT,STOP_LONG
0,13,13,Business,Cary,Cary,0.8,Meeting,North Carolina,North Carolina,"Cary, North Carolina","Cary, North Carolina",35.770437,-78.830308,35.770437,-78.830308
1,8,8,Business,Cary,Morrisville,8.3,Meeting,North Carolina,North Carolina,"Cary, North Carolina","Morrisville, North Carolina",35.770437,-78.830308,35.832915,-78.839616
2,12,12,Business,Jamaica,New York,16.5,Customer Visit,New York,New York,"Jamaica, New York","New York, New York",40.701520,-73.796421,40.558996,-93.475957
3,18,18,Business,Elmhurst,New York,7.5,Meeting,New York,New York,"Elmhurst, New York","New York, New York",40.738719,-73.879460,40.558996,-93.475957
4,19,19,Business,Midtown,East Harlem,6.2,Meeting,New York,New York,"Midtown, New York","East Harlem, New York",40.750488,-73.983924,40.800435,-73.942249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,18,18,Business,Cary,Cary,4.2,Errand/Supplies,North Carolina,North Carolina,"Cary, North Carolina","Cary, North Carolina",35.770437,-78.830308,35.770437,-78.830308
341,20,20,Business,Cary,Cary,4.1,Meal/Entertain,North Carolina,North Carolina,"Cary, North Carolina","Cary, North Carolina",35.770437,-78.830308,35.770437,-78.830308
342,17,18,Business,Cary,Morrisville,3.0,Meal/Entertain,North Carolina,North Carolina,"Cary, North Carolina","Morrisville, North Carolina",35.770437,-78.830308,35.832915,-78.839616
343,20,20,Business,Morrisville,Cary,3.1,Customer Visit,North Carolina,North Carolina,"Morrisville, North Carolina","Cary, North Carolina",35.832915,-78.839616,35.770437,-78.830308
344,14,14,Business,Cary,Morrisville,10.6,Meeting,North Carolina,North Carolina,"Cary, North Carolina","Morrisville, North Carolina",35.770437,-78.830308,35.832915,-78.839616